package linux

import (
	"encoding/base64"
	"fmt"
	"io"
	"net"
	"strings"

	"cloister.io/internal/vm"
)

const (
	colimaDnsmasqConfPath        = "/etc/dnsmasq.d/01-colima.conf"
	guestResolvConfPath          = "/etc/resolv.conf"
	guestDNSInspectMarker        = "cloister-guest-dns-inspection-v1"
	guestDNSRestartTimeoutMarker = "cloister-guest-dns-restart-timeout"
	guestDNSVerifyTimeoutMarker  = "cloister-guest-dns-verify-timeout"
)

// GuestDNSResult describes the observable outcome of reconciling Colima's
// guest DNS configuration.
type GuestDNSResult struct {
	Skipped           bool
	ConfigChanged     bool
	ResolvConfChanged bool
	ServiceRestarted  bool
	Warning           string
}

// Changed reports whether reconciliation wrote a file or restarted dnsmasq.
func (r GuestDNSResult) Changed() bool {
	return r.ConfigChanged || r.ResolvConfChanged || r.ServiceRestarted
}

// Status returns a concise user-facing description of the reconciliation.
func (r GuestDNSResult) Status() string {
	if r.Skipped {
		return fmt.Sprintf("skipped: %s does not exist", colimaDnsmasqConfPath)
	}
	if r.Warning != "" {
		if r.Changed() {
			return r.repairedStatus() + "; " + r.Warning
		}
		return r.Warning
	}
	if !r.Changed() {
		return "already correct"
	}

	return r.repairedStatus()
}

func (r GuestDNSResult) repairedStatus() string {
	var changes []string
	if r.ConfigChanged {
		changes = append(changes, "sanitized dnsmasq config")
	}
	if r.ResolvConfChanged {
		changes = append(changes, "updated "+guestResolvConfPath)
	}
	if r.ServiceRestarted {
		changes = append(changes, "restarted dnsmasq")
	}
	return "repaired (" + strings.Join(changes, ", ") + ")"
}

func (r *GuestDNSResult) addWarning(message string) {
	if r.Warning == "" {
		r.Warning = "warning: " + message
		return
	}
	r.Warning += "; " + message
}

// sanitizeDnsmasqConf removes address-specific binding directives while
// preserving every other existing byte. It adds local-service so wildcard
// binding accepts queries only from clients on locally connected subnets.
func sanitizeDnsmasqConf(input string) string {
	var output strings.Builder
	hasLocalService := false
	for _, line := range strings.SplitAfter(input, "\n") {
		directive := strings.TrimSpace(strings.TrimSuffix(line, "\n"))
		directive = strings.TrimSuffix(directive, "\r")
		if isDnsmasqBindDirective(directive) {
			continue
		}
		if directive == "local-service" || directive == "local-service=net" || directive == "local-service=host" {
			hasLocalService = true
		}
		output.WriteString(line)
	}
	if hasLocalService {
		return output.String()
	}

	newline := "\n"
	if strings.Contains(input, "\r\n") {
		newline = "\r\n"
	}
	sanitized := output.String()
	if sanitized == "" {
		return "local-service" + newline
	}
	if strings.HasSuffix(sanitized, "\n") {
		return sanitized + "local-service" + newline
	}
	return sanitized + newline + "local-service"
}

func isDnsmasqBindDirective(line string) bool {
	if strings.HasPrefix(line, "listen-address=") || strings.HasPrefix(line, "interface=") {
		return true
	}
	for _, directive := range []string{"bind-interfaces", "bind-dynamic"} {
		if line == directive || strings.HasPrefix(line, directive+"=") || strings.HasPrefix(line, directive+" ") || strings.HasPrefix(line, directive+"\t") {
			return true
		}
	}
	return false
}

// renderResolvConf returns the complete Cloister-managed resolver content.
// The guest address keeps containers routed through dnsmasq. When available,
// the stable default gateway provides a fallback if that address becomes stale.
func renderResolvConf(guestIPv4 string, fallbackAddresses ...string) string {
	var content strings.Builder
	fmt.Fprintf(&content, "# Managed by cloister\nnameserver %s\n", guestIPv4)
	seen := map[string]bool{guestIPv4: true}
	for _, fallbackAddress := range fallbackAddresses {
		if fallbackAddress == "" || seen[fallbackAddress] {
			continue
		}
		fmt.Fprintf(&content, "nameserver %s\n", fallbackAddress)
		seen[fallbackAddress] = true
	}
	content.WriteString("options timeout:1 attempts:2\n")
	return content.String()
}

func resolvConfNameservers(content string) []string {
	var nameservers []string
	for _, line := range strings.Split(content, "\n") {
		fields := strings.Fields(line)
		if len(fields) >= 2 && fields[0] == "nameserver" {
			nameservers = append(nameservers, fields[1])
		}
	}
	return nameservers
}

// resolvConfIsManaged identifies non-empty content whose first line names
// Colima or Cloister as its manager. The reconciler handles absent and empty
// files separately because neither can contain foreign resolver settings.
func resolvConfIsManaged(content string) bool {
	header, _, _ := strings.Cut(content, "\n")
	header = strings.TrimSuffix(header, "\r")
	return header == "# Generated by Colima" || header == "# Managed by cloister"
}

type guestDNSState struct {
	missing               bool
	resolvPresent         bool
	resolvDanglingSymlink bool
	guestIPv4             string
	gatewayIPv4           string
	serviceActive         bool
	serviceCheckTimedOut  bool
	dnsmasqConf           string
	resolvConf            string
}

// ReconcileGuestDNS repairs Colima's dnsmasq binding and resolver files using
// the guest's current network state. It makes no VM lifecycle changes.
func ReconcileGuestDNS(profile string, backend vm.Backend, out io.Writer) (GuestDNSResult, error) {
	state, err := inspectGuestDNS(profile, backend)
	if err != nil {
		return GuestDNSResult{}, err
	}
	if state.missing {
		result := GuestDNSResult{Skipped: true}
		writeGuestDNSStatus(out, result)
		return result, nil
	}

	sanitized := sanitizeDnsmasqConf(state.dnsmasqConf)
	result := GuestDNSResult{ConfigChanged: sanitized != state.dnsmasqConf}

	if state.serviceCheckTimedOut {
		result.addWarning("timed out checking whether dnsmasq is active")
	}

	var desiredResolv string
	resolvWritable := !state.resolvPresent || (!state.resolvDanglingSymlink && state.resolvConf == "") || resolvConfIsManaged(state.resolvConf)
	if !resolvWritable {
		result.addWarning(fmt.Sprintf("%s is not managed by Colima or cloister; left it unchanged", guestResolvConfPath))
	} else {
		if err := validateGuestIPv4("eth0", state.guestIPv4); err != nil {
			return GuestDNSResult{}, err
		}
		gatewayIPv4 := state.gatewayIPv4
		var fallbackAddresses []string
		if err := validateGuestIPv4("default gateway", gatewayIPv4); err != nil {
			fallbackAddresses = resolvConfNameservers(state.resolvConf)
			result.addWarning("default gateway IPv4 is unavailable; gateway fallback omitted")
		} else {
			fallbackAddresses = []string{gatewayIPv4}
		}
		desiredResolv = renderResolvConf(state.guestIPv4, fallbackAddresses...)
		result.ResolvConfChanged = !state.resolvPresent || state.resolvConf != desiredResolv
	}
	restartNeeded := result.ConfigChanged || (!state.serviceActive && !state.serviceCheckTimedOut)

	if result.ConfigChanged || result.ResolvConfChanged || restartNeeded {
		var rootScript strings.Builder
		rootScript.WriteString("set -euo pipefail\n")
		if result.ResolvConfChanged {
			rootScript.WriteString(atomicGuestWriteExactScriptWithMode(guestResolvConfPath, desiredResolv, false, "0644"))
		}
		if result.ConfigChanged {
			rootScript.WriteString(atomicGuestWriteExactScriptWithMode(colimaDnsmasqConfPath, sanitized, false, "0644"))
		}
		if restartNeeded {
			rootScript.WriteString(guestDNSRestartScript())
		}

		script := "sudo -n bash -c " + shellSingleQuote(rootScript.String()) + "\n"
		guestOutput, err := backend.SSHScriptTo(profile, script, out)
		if err != nil {
			return GuestDNSResult{}, fmt.Errorf("repairing guest DNS: %w", err)
		}
		if restartNeeded {
			switch {
			case strings.Contains(guestOutput, guestDNSRestartTimeoutMarker):
				result.addWarning("timed out restarting dnsmasq")
			case strings.Contains(guestOutput, guestDNSVerifyTimeoutMarker):
				result.ServiceRestarted = true
				result.addWarning("timed out verifying dnsmasq after restart")
			default:
				result.ServiceRestarted = true
			}
		}
	}

	writeGuestDNSStatus(out, result)
	return result, nil
}

func guestDNSRestartScript() string {
	return `restart_status=0
timeout --kill-after=2s 15s systemctl restart dnsmasq || restart_status=$?
if [ "$restart_status" -eq 124 ] || [ "$restart_status" -eq 137 ]; then
	printf '%s\n' '` + guestDNSRestartTimeoutMarker + `'
elif [ "$restart_status" -ne 0 ]; then
	exit "$restart_status"
else
	active_status=0
	timeout --kill-after=2s 5s systemctl is-active --quiet dnsmasq || active_status=$?
	if [ "$active_status" -eq 124 ] || [ "$active_status" -eq 137 ]; then
		printf '%s\n' '` + guestDNSVerifyTimeoutMarker + `'
	elif [ "$active_status" -ne 0 ]; then
		exit "$active_status"
	fi
fi
`
}

func writeGuestDNSStatus(out io.Writer, result GuestDNSResult) {
	if out != nil {
		_, _ = fmt.Fprintf(out, "Guest DNS: %s\n", result.Status())
	}
}

func validateGuestIPv4(name, address string) error {
	ip := net.ParseIP(address)
	if ip == nil || ip.To4() == nil || strings.Contains(address, ":") {
		return fmt.Errorf("guest DNS: could not determine current %s IPv4 address", name)
	}
	return nil
}

func inspectGuestDNS(profile string, backend vm.Backend) (guestDNSState, error) {
	output, err := backend.SSHCapture(profile, guestDNSInspectionScript())
	if err != nil {
		return guestDNSState{}, fmt.Errorf("inspecting guest DNS: %w", err)
	}
	return parseGuestDNSInspection(output)
}

func guestDNSInspectionScript() string {
	return `set -euo pipefail
conf=/etc/dnsmasq.d/01-colima.conf
resolv=/etc/resolv.conf
printf '%s\n' '` + guestDNSInspectMarker + `'
if [ ! -L "$conf" ] && [ ! -e "$conf" ]; then
	printf '%s\n' 'state=missing'
	exit 0
fi
if [ ! -f "$conf" ]; then
	printf '%s\n' "$conf is not a regular file" >&2
	exit 1
fi
guest_ipv4=$(ip -4 -o addr show dev eth0 scope global | awk 'NR == 1 { sub(/\/.*/, "", $4); print $4 }')
gateway_ipv4=$(ip -4 route show default dev eth0 | awk '$1 == "default" { print $3; exit }')
service_active=0
service_check_timeout=0
service_status=0
timeout --kill-after=2s 5s systemctl is-active --quiet dnsmasq || service_status=$?
if [ "$service_status" -eq 0 ]; then
	service_active=1
elif [ "$service_status" -eq 124 ] || [ "$service_status" -eq 137 ]; then
	service_check_timeout=1
fi
dnsmasq_conf=$(sudo -n base64 -- "$conf" | tr -d '\n\r')
resolv_present=0
resolv_dangling_symlink=0
resolv_conf=
if [ -L "$resolv" ] || [ -e "$resolv" ]; then
	resolv_present=1
	if [ -L "$resolv" ] && [ ! -e "$resolv" ]; then
		resolv_dangling_symlink=1
	else
		resolv_conf=$(sudo -n base64 -- "$resolv" | tr -d '\n\r')
	fi
fi
printf '%s\n' 'state=present'
printf 'guest_ipv4=%s\n' "$guest_ipv4"
printf 'gateway_ipv4=%s\n' "$gateway_ipv4"
printf 'service_active=%s\n' "$service_active"
printf 'service_check_timeout=%s\n' "$service_check_timeout"
printf 'dnsmasq_conf=%s\n' "$dnsmasq_conf"
printf 'resolv_present=%s\n' "$resolv_present"
printf 'resolv_dangling_symlink=%s\n' "$resolv_dangling_symlink"
printf 'resolv_conf=%s\n' "$resolv_conf"
`
}

func parseGuestDNSInspection(output string) (guestDNSState, error) {
	lines := strings.Split(output, "\n")
	marker := false
	values := make(map[string]string)
	for _, line := range lines {
		if strings.TrimSuffix(line, "\r") == guestDNSInspectMarker {
			marker = true
			continue
		}
		key, value, ok := strings.Cut(strings.TrimSuffix(line, "\r"), "=")
		if marker && ok {
			values[key] = value
		}
	}
	if !marker {
		return guestDNSState{}, fmt.Errorf("inspecting guest DNS: response marker was missing")
	}
	if values["state"] == "missing" {
		return guestDNSState{missing: true}, nil
	}
	if values["state"] != "present" {
		return guestDNSState{}, fmt.Errorf("inspecting guest DNS: unrecognized state %q", values["state"])
	}

	decode := func(key string) (string, error) {
		encoded, ok := values[key]
		if !ok {
			return "", fmt.Errorf("inspecting guest DNS: response omitted %s", key)
		}
		decoded, err := base64.StdEncoding.DecodeString(encoded)
		if err != nil {
			return "", fmt.Errorf("inspecting guest DNS: invalid %s content: %w", key, err)
		}
		return string(decoded), nil
	}
	dnsmasqConf, err := decode("dnsmasq_conf")
	if err != nil {
		return guestDNSState{}, err
	}
	resolvConf, err := decode("resolv_conf")
	if err != nil {
		return guestDNSState{}, err
	}
	for _, key := range []string{"service_active", "service_check_timeout", "resolv_present", "resolv_dangling_symlink"} {
		if values[key] != "0" && values[key] != "1" {
			return guestDNSState{}, fmt.Errorf("inspecting guest DNS: invalid %s state %q", key, values[key])
		}
	}
	return guestDNSState{
		resolvPresent:         values["resolv_present"] == "1",
		resolvDanglingSymlink: values["resolv_dangling_symlink"] == "1",
		guestIPv4:             values["guest_ipv4"],
		gatewayIPv4:           values["gateway_ipv4"],
		serviceActive:         values["service_active"] == "1",
		serviceCheckTimedOut:  values["service_check_timeout"] == "1",
		dnsmasqConf:           dnsmasqConf,
		resolvConf:            resolvConf,
	}, nil
}
