package linux

import (
	"encoding/base64"
	"strings"
	"testing"

	"cloister.io/internal/vm"
)

func TestSanitizeDnsmasqConf(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		input string
		want  string
	}{
		{
			name: "removes stale binding directives and preserves resolver rules",
			input: "# Generated by Colima\n" +
				"listen-address=192.168.5.1\n" +
				"bind-interfaces\n" +
				"bind-dynamic\n" +
				"interface=eth0\n" +
				"address=/host.docker.internal/192.168.5.2\n" +
				"server=192.168.5.2\n" +
				"# retain this comment\n",
			want: "# Generated by Colima\n" +
				"address=/host.docker.internal/192.168.5.2\n" +
				"server=192.168.5.2\n" +
				"# retain this comment\n" +
				"local-service\n",
		},
		{
			name:  "preserves already sanitized input byte for byte",
			input: "address=/host.docker.internal/192.168.5.2\r\nserver=192.168.5.2\r\nlocal-service",
			want:  "address=/host.docker.internal/192.168.5.2\r\nserver=192.168.5.2\r\nlocal-service",
		},
		{
			name:  "does not treat commented directives as active",
			input: "# listen-address=192.168.5.1\n# bind-interfaces\n",
			want:  "# listen-address=192.168.5.1\n# bind-interfaces\nlocal-service\n",
		},
		{
			name:  "keeps existing local service directive idempotent",
			input: "address=/host.docker.internal/192.168.5.2\nlocal-service\nserver=192.168.5.2\n",
			want:  "address=/host.docker.internal/192.168.5.2\nlocal-service\nserver=192.168.5.2\n",
		},
		{
			name:  "keeps local service host directive idempotent",
			input: "address=/host.docker.internal/192.168.5.2\nlocal-service=host\n",
			want:  "address=/host.docker.internal/192.168.5.2\nlocal-service=host\n",
		},
		{
			name:  "terminates local service in an otherwise empty config",
			input: "",
			want:  "local-service\n",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			if got := sanitizeDnsmasqConf(test.input); got != test.want {
				t.Errorf("sanitizeDnsmasqConf() = %q, want %q", got, test.want)
			}
		})
	}
}

func TestRenderResolvConf(t *testing.T) {
	t.Parallel()

	want := "# Managed by cloister\n" +
		"nameserver 192.168.5.3\n" +
		"nameserver 192.168.5.2\n" +
		"options timeout:1 attempts:2\n"
	if got := renderResolvConf("192.168.5.3", "192.168.5.2"); got != want {
		t.Fatalf("renderResolvConf() = %q, want %q", got, want)
	}
}

func TestResolvConfIsManaged(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{name: "Colima header", content: "# Generated by Colima\nnameserver 192.168.5.1\n", want: true},
		{name: "Cloister header", content: "# Managed by cloister\nnameserver 192.168.5.3\n", want: true},
		{name: "unmanaged resolver", content: "# Managed by an administrator\nnameserver 10.0.0.53\n", want: false},
		{name: "managed text after first line", content: "nameserver 10.0.0.53\n# Generated by Colima\n", want: false},
		{name: "empty file", content: "", want: false},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			if got := resolvConfIsManaged(test.content); got != test.want {
				t.Errorf("resolvConfIsManaged() = %v, want %v", got, test.want)
			}
		})
	}
}

func TestReconcileGuestDNSSkipsMissingDnsmasqConfig(t *testing.T) {
	backend := dnsInspectionBackend(guestDNSInspectMarker + "\nstate=missing\n")
	var out strings.Builder

	result, err := ReconcileGuestDNS("dev", backend, &out)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if !result.Skipped || result.Changed() {
		t.Fatalf("result = %#v, want skipped without changes", result)
	}
	if !strings.Contains(out.String(), "skipped") || !strings.Contains(out.String(), colimaDnsmasqConfPath) {
		t.Errorf("status = %q, want clear missing-config message", out.String())
	}
	if len(backend.SSHScriptCalls) != 1 {
		t.Fatalf("guest calls = %d, want inspection only", len(backend.SSHScriptCalls))
	}
}

func TestReconcileGuestDNSRefusesUnmanagedResolvConf(t *testing.T) {
	conf := "address=/host.docker.internal/192.168.5.2\nserver=192.168.5.2\nlocal-service\n"
	resolv := "# Managed by an administrator\nnameserver 10.0.0.53\n"
	backend := dnsInspectionBackend(presentDNSInspection(conf, resolv, true))

	result, err := ReconcileGuestDNS("dev", backend, nil)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if result.Warning == "" || !strings.Contains(result.Warning, guestResolvConfPath) {
		t.Fatalf("warning = %q, want unmanaged file named", result.Warning)
	}
	if result.ResolvConfChanged || result.Changed() {
		t.Fatalf("result = %#v, want unmanaged resolver left untouched", result)
	}
	if len(backend.SSHScriptCalls) != 1 {
		t.Fatalf("guest calls = %d, want inspection only", len(backend.SSHScriptCalls))
	}
}

func TestReconcileGuestDNSReportsAlreadyCorrectWithoutWriting(t *testing.T) {
	conf := "address=/host.docker.internal/192.168.5.2\nserver=192.168.5.2\nlocal-service\n"
	resolv := renderResolvConf("192.168.5.3", "192.168.5.2")
	backend := dnsInspectionBackend(presentDNSInspection(conf, resolv, true))
	var out strings.Builder

	result, err := ReconcileGuestDNS("dev", backend, &out)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if result.Changed() || result.Status() != "already correct" {
		t.Fatalf("result = %#v, status = %q", result, result.Status())
	}
	if !strings.Contains(out.String(), "already correct") {
		t.Errorf("status output = %q", out.String())
	}
	if len(backend.SSHScriptCalls) != 1 {
		t.Fatalf("guest calls = %d, want inspection only", len(backend.SSHScriptCalls))
	}
}

func TestReconcileGuestDNSSanitizesAndRestartsDnsmasq(t *testing.T) {
	conf := "listen-address=192.168.5.1\nbind-interfaces\naddress=/host.docker.internal/192.168.5.2\n"
	resolv := "# Generated by Colima\nnameserver 192.168.5.1\n"
	backend := dnsInspectionBackend(presentDNSInspection(conf, resolv, true))

	result, err := ReconcileGuestDNS("dev", backend, nil)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if !result.ConfigChanged || !result.ResolvConfChanged || !result.ServiceRestarted {
		t.Fatalf("result = %#v, want both files repaired and dnsmasq restarted", result)
	}
	if len(backend.SSHScriptCalls) != 2 {
		t.Fatalf("guest calls = %d, want inspection and one repair", len(backend.SSHScriptCalls))
	}
	repair := backend.SSHScriptCalls[1].Script
	wantResolv := renderResolvConf("192.168.5.3", "192.168.5.2")
	wantDnsmasq := "address=/host.docker.internal/192.168.5.2\nlocal-service\n"
	if got := repairWritePayload(t, repair, guestResolvConfPath); got != wantResolv {
		t.Errorf("resolv.conf payload = %q, want %q", got, wantResolv)
	}
	if got := repairWritePayload(t, repair, colimaDnsmasqConfPath); got != wantDnsmasq {
		t.Errorf("dnsmasq payload = %q, want %q", got, wantDnsmasq)
	}
	assertRepairOperationOrder(t, repair, guestResolvConfPath, colimaDnsmasqConfPath, "timeout --kill-after=2s 15s systemctl restart dnsmasq")
	for _, want := range []string{"set -euo pipefail", "chmod 0644", "timeout --kill-after=2s 15s systemctl restart dnsmasq", "timeout --kill-after=2s 5s systemctl is-active --quiet dnsmasq"} {
		if !strings.Contains(repair, want) {
			t.Errorf("repair script does not contain %q:\n%s", want, repair)
		}
	}
}

func TestReconcileGuestDNSDoesNotRestartForResolvConfOnly(t *testing.T) {
	conf := "address=/host.docker.internal/192.168.5.2\nserver=192.168.5.2\nlocal-service\n"
	resolv := "# Generated by Colima\nnameserver 192.168.5.1\n"
	backend := dnsInspectionBackend(presentDNSInspection(conf, resolv, true))

	result, err := ReconcileGuestDNS("dev", backend, nil)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if !result.ResolvConfChanged || result.ConfigChanged || result.ServiceRestarted {
		t.Fatalf("result = %#v, want only resolv.conf changed", result)
	}
	if repair := backend.SSHScriptCalls[1].Script; strings.Contains(repair, "systemctl restart dnsmasq") {
		t.Errorf("resolv.conf-only repair restarted dnsmasq:\n%s", repair)
	} else if got, want := repairWritePayload(t, repair, guestResolvConfPath), renderResolvConf("192.168.5.3", "192.168.5.2"); got != want {
		t.Errorf("resolv.conf payload = %q, want %q", got, want)
	}
}

func TestReconcileGuestDNSRestartsInactiveServiceWithoutRewritingFiles(t *testing.T) {
	conf := "address=/host.docker.internal/192.168.5.2\nserver=192.168.5.2\nlocal-service\n"
	resolv := renderResolvConf("192.168.5.3", "192.168.5.2")
	backend := dnsInspectionBackend(presentDNSInspection(conf, resolv, false))

	result, err := ReconcileGuestDNS("dev", backend, nil)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if result.ConfigChanged || result.ResolvConfChanged || !result.ServiceRestarted {
		t.Fatalf("result = %#v, want only dnsmasq restarted", result)
	}
	repair := backend.SSHScriptCalls[1].Script
	if !strings.Contains(repair, "systemctl restart dnsmasq") {
		t.Errorf("inactive service was not restarted:\n%s", repair)
	}
	if strings.Contains(repair, "cloister-tmp") {
		t.Errorf("inactive-service repair rewrote an already-correct file:\n%s", repair)
	}
}

func TestReconcileGuestDNSCreatesAbsentResolvConf(t *testing.T) {
	conf := "address=/host.docker.internal/192.168.5.2\nlocal-service\n"
	backend := dnsInspectionBackend(dnsInspection(conf, "", false, true, "192.168.5.2", false))

	result, err := ReconcileGuestDNS("dev", backend, nil)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if !result.ResolvConfChanged || result.ConfigChanged || result.ServiceRestarted || result.Warning != "" {
		t.Fatalf("result = %#v, want absent resolv.conf created without restart", result)
	}
	repair := backend.SSHScriptCalls[1].Script
	if got, want := repairWritePayload(t, repair, guestResolvConfPath), renderResolvConf("192.168.5.3", "192.168.5.2"); got != want {
		t.Errorf("resolv.conf payload = %q, want %q", got, want)
	}
}

func TestReconcileGuestDNSReplacesEmptyResolvConf(t *testing.T) {
	conf := "address=/host.docker.internal/192.168.5.2\nlocal-service\n"
	backend := dnsInspectionBackend(dnsInspection(conf, "", true, true, "192.168.5.2", false))

	result, err := ReconcileGuestDNS("dev", backend, nil)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if !result.ResolvConfChanged || result.Warning != "" {
		t.Fatalf("result = %#v, want empty resolv.conf replaced", result)
	}
	if got, want := repairWritePayload(t, backend.SSHScriptCalls[1].Script, guestResolvConfPath), renderResolvConf("192.168.5.3", "192.168.5.2"); got != want {
		t.Errorf("resolv.conf payload = %q, want %q", got, want)
	}
}

func TestReconcileGuestDNSMissingGatewayPreservesExistingFallbacks(t *testing.T) {
	conf := "listen-address=192.168.5.1\nbind-interfaces\naddress=/host.docker.internal/192.168.5.2\n"
	resolv := "# Generated by Colima\n" +
		"nameserver 192.168.5.3\n" +
		"nameserver 10.0.0.53\n" +
		"nameserver 192.168.5.3\n" +
		"nameserver 10.0.0.54\n" +
		"nameserver 10.0.0.53\n"
	backend := dnsInspectionBackend(dnsInspection(conf, resolv, true, true, "", false))

	result, err := ReconcileGuestDNS("dev", backend, nil)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if !result.ConfigChanged || !result.ResolvConfChanged || !result.ServiceRestarted {
		t.Fatalf("result = %#v, want config and resolver repaired with restart", result)
	}
	if !strings.Contains(result.Warning, "fallback omitted") {
		t.Fatalf("warning = %q, want missing gateway reported", result.Warning)
	}
	repair := backend.SSHScriptCalls[1].Script
	wantResolv := renderResolvConf("192.168.5.3", "10.0.0.53", "10.0.0.54")
	if got := repairWritePayload(t, repair, guestResolvConfPath); got != wantResolv {
		t.Errorf("resolv.conf payload = %q, want %q", got, wantResolv)
	}
	if got, want := repairWritePayload(t, repair, colimaDnsmasqConfPath), "address=/host.docker.internal/192.168.5.2\nlocal-service\n"; got != want {
		t.Errorf("dnsmasq payload = %q, want %q", got, want)
	}
	assertRepairOperationOrder(t, repair, guestResolvConfPath, colimaDnsmasqConfPath, "timeout --kill-after=2s 15s systemctl restart dnsmasq")
}

func TestReconcileGuestDNSMissingGatewayWithoutFallbackWritesGuestOnly(t *testing.T) {
	conf := "address=/host.docker.internal/192.168.5.2\nlocal-service\n"
	backend := dnsInspectionBackend(dnsInspection(conf, "", true, true, "", false))

	result, err := ReconcileGuestDNS("dev", backend, nil)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if !result.ResolvConfChanged || result.ConfigChanged || result.ServiceRestarted {
		t.Fatalf("result = %#v, want only resolver created", result)
	}
	if !strings.Contains(result.Warning, "gateway fallback omitted") {
		t.Fatalf("warning = %q, want missing gateway fallback reported", result.Warning)
	}
	if got, want := repairWritePayload(t, backend.SSHScriptCalls[1].Script, guestResolvConfPath), renderResolvConf("192.168.5.3"); got != want {
		t.Errorf("resolv.conf payload = %q, want %q", got, want)
	}
}

func TestReconcileGuestDNSRefusesDanglingResolvConfSymlink(t *testing.T) {
	conf := "address=/host.docker.internal/192.168.5.2\nlocal-service\n"
	backend := dnsInspectionBackend(dnsInspectionWithDanglingResolv(conf, "", true, true, "192.168.5.2", false, true))

	result, err := ReconcileGuestDNS("dev", backend, nil)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if result.Changed() || result.ResolvConfChanged {
		t.Fatalf("result = %#v, want dangling resolver symlink untouched", result)
	}
	if !strings.Contains(result.Warning, guestResolvConfPath) || !strings.Contains(result.Warning, "left it unchanged") {
		t.Fatalf("warning = %q, want refused resolver named", result.Warning)
	}
	if len(backend.SSHScriptCalls) != 1 {
		t.Fatalf("guest calls = %d, want inspection only", len(backend.SSHScriptCalls))
	}
}

func TestReconcileGuestDNSActivityCheckTimeoutDoesNotRestartCorrectService(t *testing.T) {
	conf := "address=/host.docker.internal/192.168.5.2\nlocal-service\n"
	resolv := renderResolvConf("192.168.5.3", "192.168.5.2")
	backend := dnsInspectionBackend(dnsInspection(conf, resolv, true, false, "192.168.5.2", true))

	result, err := ReconcileGuestDNS("dev", backend, nil)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v", err)
	}
	if result.Changed() || result.ServiceRestarted {
		t.Fatalf("result = %#v, want timed-out activity check to leave service alone", result)
	}
	if !strings.Contains(result.Warning, "timed out checking") {
		t.Fatalf("warning = %q, want activity-check timeout", result.Warning)
	}
	if len(backend.SSHScriptCalls) != 1 {
		t.Fatalf("guest calls = %d, want inspection only", len(backend.SSHScriptCalls))
	}
}

func TestGuestDNSStatusIncludesRepairAndWarning(t *testing.T) {
	result := GuestDNSResult{
		ConfigChanged:    true,
		ServiceRestarted: true,
		Warning:          "warning: default gateway IPv4 is unavailable; resolver fallback omitted",
	}
	status := result.Status()
	for _, want := range []string{"sanitized dnsmasq config", "restarted dnsmasq", "fallback omitted"} {
		if !strings.Contains(status, want) {
			t.Errorf("status = %q, want %q", status, want)
		}
	}
}

func TestGuestDNSInspectionUsesPortableBase64AndTimeout(t *testing.T) {
	script := guestDNSInspectionScript()
	if strings.Contains(script, "base64 -w") {
		t.Errorf("inspection uses GNU-only base64 wrapping flag:\n%s", script)
	}
	for _, want := range []string{"[ ! -L \"$conf\" ] && [ ! -e \"$conf\" ]", "[ -L \"$resolv\" ] || [ -e \"$resolv\" ]", "base64 -- \"$conf\" | tr -d '\\n\\r'", "base64 -- \"$resolv\" | tr -d '\\n\\r'", "timeout --kill-after=2s 5s systemctl is-active"} {
		if !strings.Contains(script, want) {
			t.Errorf("inspection script does not contain %q:\n%s", want, script)
		}
	}
}

func TestReconcileGuestDNSReportsRestartTimeoutAsWarning(t *testing.T) {
	conf := "address=/host.docker.internal/192.168.5.2\nlocal-service\n"
	resolv := renderResolvConf("192.168.5.3", "192.168.5.2")
	backend := dnsInspectionBackend(presentDNSInspection(conf, resolv, false))
	backend.SSHScriptOut = guestDNSRestartTimeoutMarker + "\n"

	result, err := ReconcileGuestDNS("dev", backend, nil)
	if err != nil {
		t.Fatalf("ReconcileGuestDNS() error = %v, want non-fatal timeout warning", err)
	}
	if result.ServiceRestarted || !strings.Contains(result.Warning, "timed out restarting dnsmasq") {
		t.Fatalf("result = %#v, want restart timeout warning without success claim", result)
	}
}

func dnsInspectionBackend(output string) *vm.MockBackend {
	return &vm.MockBackend{SSHCaptureFunc: func(_, _ string) (string, error) {
		return output, nil
	}}
}

func presentDNSInspection(conf, resolv string, active bool) string {
	return dnsInspection(conf, resolv, true, active, "192.168.5.2", false)
}

func dnsInspection(conf, resolv string, resolvPresent, active bool, gateway string, serviceCheckTimedOut bool) string {
	return dnsInspectionWithDanglingResolv(conf, resolv, resolvPresent, active, gateway, serviceCheckTimedOut, false)
}

func dnsInspectionWithDanglingResolv(conf, resolv string, resolvPresent, active bool, gateway string, serviceCheckTimedOut, resolvDangling bool) string {
	service := "0"
	if active {
		service = "1"
	}
	serviceTimeout := "0"
	if serviceCheckTimedOut {
		serviceTimeout = "1"
	}
	present := "0"
	if resolvPresent {
		present = "1"
	}
	dangling := "0"
	if resolvDangling {
		dangling = "1"
	}
	return guestDNSInspectMarker + "\n" +
		"state=present\n" +
		"guest_ipv4=192.168.5.3\n" +
		"gateway_ipv4=" + gateway + "\n" +
		"service_active=" + service + "\n" +
		"service_check_timeout=" + serviceTimeout + "\n" +
		"dnsmasq_conf=" + base64.StdEncoding.EncodeToString([]byte(conf)) + "\n" +
		"resolv_present=" + present + "\n" +
		"resolv_dangling_symlink=" + dangling + "\n" +
		"resolv_conf=" + base64.StdEncoding.EncodeToString([]byte(resolv)) + "\n"
}

func repairWritePayload(t *testing.T, script, path string) string {
	t.Helper()
	pathAt := strings.Index(script, path)
	if pathAt < 0 {
		t.Fatalf("repair script has no write for %s:\n%s", path, script)
	}
	for _, line := range strings.Split(script[pathAt:], "\n") {
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, "if ! printf ") || !strings.Contains(trimmed, " | base64 --decode") {
			continue
		}
		fields := strings.Fields(trimmed)
		if len(fields) < 7 {
			t.Fatalf("could not parse payload write for %s: %q", path, line)
		}
		decoded, err := base64.StdEncoding.DecodeString(fields[4])
		if err != nil {
			t.Fatalf("decode payload for %s: %v", path, err)
		}
		return string(decoded)
	}
	t.Fatalf("repair script has no payload for %s:\n%s", path, script)
	return ""
}

func assertRepairOperationOrder(t *testing.T, script string, operations ...string) {
	t.Helper()
	previous := -1
	for _, operation := range operations {
		index := strings.Index(script, operation)
		if index < 0 {
			t.Fatalf("repair script has no %q operation:\n%s", operation, script)
		}
		if index <= previous {
			t.Fatalf("repair operation %q is out of order in:\n%s", operation, script)
		}
		previous = index
	}
}
