package vm

// Backend is the abstraction layer for VM lifecycle management. Implementations
// of this interface wrap a specific hypervisor CLI (e.g. Colima, Lume) so that
// higher-level cloister logic can remain decoupled from any single tool.
//
// Each method accepts a profile name that identifies a cloister-managed VM.
// Implementations are responsible for translating the profile name into the
// backend-specific instance identifier (e.g. by prepending a vendor prefix).
type Backend interface {
	// Start creates or resumes the VM for the given profile with the supplied
	// resource allocation. Each entry in mounts describes a host directory to
	// bind into the guest. When verbose is true, hypervisor output is forwarded
	// to stderr so the caller can observe progress in real time.
	Start(profile string, cpus, memoryGB, diskGB int, mounts []Mount, verbose bool) error

	// Stop gracefully shuts down the running VM for the given profile. It must
	// be idempotent: stopping an already-stopped VM must not return an error.
	// When verbose is true, hypervisor output is forwarded to stderr.
	Stop(profile string, verbose bool) error

	// Delete permanently destroys the VM for the given profile and releases all
	// associated resources. When verbose is true, hypervisor output is forwarded
	// to stderr.
	Delete(profile string, verbose bool) error

	// Exists reports whether a VM instance for the given profile is registered
	// with the hypervisor, regardless of whether it is currently running.
	Exists(profile string) bool

	// IsRunning reports whether the VM for the given profile is in the running
	// state. It returns false if the VM does not exist or cannot be queried.
	IsRunning(profile string) bool

	// List returns status metadata for all VM instances managed by this backend
	// that were created by cloister (i.e. carrying the cloister namespace prefix).
	// When verbose is true, hypervisor output is forwarded to stderr.
	List(verbose bool) ([]VMStatus, error)

	// SSH attaches an interactive terminal session to the VM for the given
	// profile. stdin, stdout, and stderr are connected directly to the
	// hypervisor process so the caller receives a fully functional shell.
	SSH(profile string) error

	// SSHCommand runs a non-interactive command inside the VM and returns the
	// combined stdout/stderr output. The command is executed via a login shell
	// so that the guest environment (PATH, profile scripts) is initialised.
	SSHCommand(profile string, command string) (string, error)

	// SSHInteractive runs a command inside the VM with stdin/stdout/stderr
	// connected to the current terminal. This is suitable for streaming commands
	// (e.g. following a log) that require direct terminal access.
	SSHInteractive(profile string, command string) error

	// SSHScript pipes a multi-line shell script into the VM via stdin, avoiding
	// the quoting complications that arise when embedding complex scripts in a
	// single command argument.
	SSHScript(profile string, script string) (string, error)

	// SSHConfig returns the SSH connection parameters for the given profile.
	// Callers may use the returned SSHAccess values to construct an ssh(1)
	// invocation or a programmatic SSH client connection.
	SSHConfig(profile string) SSHAccess

	// VMName returns the hypervisor-level instance name for the given profile.
	// This is distinct from the cloister profile name and is typically prefixed
	// with a backend-specific namespace string (e.g. "cloister-<profile>").
	VMName(profile string) string

	// ProfileFromVMName extracts the cloister profile name from a
	// hypervisor-level instance name. It returns an empty string when the
	// instance name was not created by cloister.
	ProfileFromVMName(vmName string) string
}

// VMStatus captures the subset of VM instance metadata that cloister needs for
// display and lifecycle decisions. The JSON tags match the field names emitted
// by `colima list --json` and are the canonical representation shared across
// all Backend implementations.
type VMStatus struct {
	Name   string `json:"name"`
	Status string `json:"status"`
	CPUs   int    `json:"cpus"`
	Memory int    `json:"memory"`
	Disk   int    `json:"disk"`
	Arch   string `json:"arch"`
}

// SSHAccess holds the connection parameters required to open an SSH session to
// a cloister-managed VM. Callers construct an ssh(1) command or a programmatic
// SSH client from these values.
type SSHAccess struct {
	// ConfigFile is the absolute path to the SSH client configuration file
	// generated by the hypervisor (e.g. the Lima-generated ssh.config file).
	// Pass this to `ssh -F` to reach the VM without specifying individual flags.
	ConfigFile string

	// HostAlias is the Host entry within ConfigFile that identifies this VM
	// (e.g. "lima-colima-cloister-work").
	HostAlias string

	// Host is the IP address or hostname used to reach the VM directly, for
	// backends that expose a routable address rather than an SSH config alias.
	Host string

	// User is the username with which to authenticate inside the VM.
	User string

	// KeyFile is the absolute path to the private key for key-based
	// authentication. May be empty when the hypervisor manages key injection
	// through its own configuration file.
	KeyFile string
}

// MockBackend is a test-only implementation of Backend that records method
// invocations and returns pre-configured canned responses. It is intended for
// use in unit tests that need to drive cloister logic without spawning real VMs.
type MockBackend struct {
	// StartCalls records the profile argument for each Start invocation, in
	// the order the calls were received.
	StartCalls []string

	// StopCalls records the profile argument for each Stop invocation.
	StopCalls []string

	// SSHCommandCalls records the profile and command argument for each
	// SSHCommand invocation.
	SSHCommandCalls []struct{ Profile, Command string }

	// SSHCommandOut is the output string returned by all SSHCommand calls.
	SSHCommandOut string

	// SSHCommandErr is the error returned by all SSHCommand calls.
	SSHCommandErr error

	// SSHScriptCalls records the profile and script argument for each
	// SSHScript invocation.
	SSHScriptCalls []struct{ Profile, Script string }

	// SSHScriptOut is the output string returned by all SSHScript calls.
	SSHScriptOut string

	// SSHScriptErr is the error returned by all SSHScript calls.
	SSHScriptErr error

	// RunningProfiles maps profile names to their simulated running state.
	// IsRunning returns the value for the queried profile (false when absent).
	RunningProfiles map[string]bool

	// SSHAccessVal is the SSHAccess value returned by all SSHConfig calls.
	SSHAccessVal SSHAccess
}

// Start records the call and returns nil. Resource arguments are accepted but
// not stored; tests that need to inspect them should subclass or extend this
// mock.
func (m *MockBackend) Start(profile string, cpus, memoryGB, diskGB int, mounts []Mount, verbose bool) error {
	m.StartCalls = append(m.StartCalls, profile)
	return nil
}

// Stop records the call and returns nil.
func (m *MockBackend) Stop(profile string, verbose bool) error {
	m.StopCalls = append(m.StopCalls, profile)
	return nil
}

// Delete records the call and returns nil. A separate DeleteCalls field is not
// provided because Delete is rarely the primary observable in unit tests; callers
// can instrument a custom mock when fine-grained Delete tracking is required.
func (m *MockBackend) Delete(profile string, verbose bool) error {
	return nil
}

// Exists always returns true, indicating the VM is registered with the backend.
// Override by embedding MockBackend in a custom struct that shadows this method.
func (m *MockBackend) Exists(profile string) bool {
	return true
}

// IsRunning returns the value recorded in RunningProfiles for the given profile,
// or false if the profile is not present in the map.
func (m *MockBackend) IsRunning(profile string) bool {
	if m.RunningProfiles == nil {
		return false
	}
	return m.RunningProfiles[profile]
}

// List returns an empty slice and no error. Tests that need to exercise listing
// behaviour should populate a custom mock with the desired VMStatus entries.
func (m *MockBackend) List(verbose bool) ([]VMStatus, error) {
	return nil, nil
}

// SSH is a no-op that returns nil. Interactive shell testing requires a real
// terminal and is therefore out of scope for unit-level mocks.
func (m *MockBackend) SSH(profile string) error {
	return nil
}

// SSHCommand records the invocation and returns SSHCommandOut and SSHCommandErr.
func (m *MockBackend) SSHCommand(profile string, command string) (string, error) {
	m.SSHCommandCalls = append(m.SSHCommandCalls, struct{ Profile, Command string }{profile, command})
	return m.SSHCommandOut, m.SSHCommandErr
}

// SSHInteractive is a no-op that returns nil. Interactive terminal testing is
// out of scope for unit-level mocks.
func (m *MockBackend) SSHInteractive(profile string, command string) error {
	return nil
}

// SSHScript records the invocation and returns SSHScriptOut and SSHScriptErr.
func (m *MockBackend) SSHScript(profile string, script string) (string, error) {
	m.SSHScriptCalls = append(m.SSHScriptCalls, struct{ Profile, Script string }{profile, script})
	return m.SSHScriptOut, m.SSHScriptErr
}

// SSHConfig returns SSHAccessVal, the pre-configured SSH connection parameters.
func (m *MockBackend) SSHConfig(profile string) SSHAccess {
	return m.SSHAccessVal
}

// VMName returns a synthetic VM name by prepending the "mock-" namespace prefix
// to the profile, mirroring the naming convention used by real backends.
func (m *MockBackend) VMName(profile string) string {
	return "mock-" + profile
}

// ProfileFromVMName strips the "mock-" prefix and returns the profile segment.
// It returns an empty string when the name does not carry the mock prefix.
func (m *MockBackend) ProfileFromVMName(vmName string) string {
	const prefix = "mock-"
	if len(vmName) <= len(prefix) || vmName[:len(prefix)] != prefix {
		return ""
	}
	return vmName[len(prefix):]
}
