package vm

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"syscall"
	"time"
)

// ProfileState is the on-disk representation of all runtime state associated
// with a single cloister profile. It supersedes the scattered flat PID files
// previously used for agent containers, port-forward processes, and tunnel
// descriptors, consolidating them into one atomically-written JSON document.
type ProfileState struct {
	// Backend identifies which hypervisor manages this profile's VM
	// (e.g. "colima" or "lume"). Stored so that commands reading state can
	// dispatch to the correct backend without re-reading the config file.
	Backend string `json:"backend"`

	// VM holds network and SSH connection metadata for the guest VM.
	VM VMState `json:"vm"`

	// Agent tracks the lifecycle of the AI agent process running inside the VM.
	Agent AgentState `json:"agent,omitempty"`

	// Tunnels is the set of active SSH port-forward tunnels associated with
	// this profile. Each entry records the host port, VM port, and the PID of
	// the ssh(1) process maintaining the tunnel.
	Tunnels []TunnelState `json:"tunnels,omitempty"`

	// Snapshots records the names and creation timestamps of the factory and
	// user-checkpoint snapshots for this profile.
	Snapshots SnapshotState `json:"snapshots,omitempty"`

	// BaseImage records which base image the profile VM was created from,
	// enabling update checks and reproducible recreation.
	BaseImage BaseImageState `json:"base_image,omitempty"`
}

// VMState holds network and SSH connection parameters for the guest VM.
// Fields are populated after the VM has started and are cleared on deletion.
type VMState struct {
	// IP is the routable IPv4 address assigned to the VM by the hypervisor.
	// Populated by backends (e.g. Lume) that expose a direct IP rather than
	// an SSH config alias.
	IP string `json:"ip,omitempty"`

	// Hostname is the DNS name under which the VM is reachable on the local
	// network (e.g. "cloister-work.local"). Used by Lume-backed profiles.
	Hostname string `json:"hostname,omitempty"`

	// LimaHost is the Host alias within the Lima-generated SSH config file
	// (e.g. "lima-colima-cloister-work"). Used by Colima-backed profiles.
	LimaHost string `json:"lima_host,omitempty"`

	// SSHConfig is the absolute path to the SSH client configuration file
	// generated by the hypervisor. Pass to `ssh -F` to reach the VM.
	SSHConfig string `json:"ssh_config,omitempty"`

	// LastEntry records the ISO-8601 timestamp of the most recent successful
	// SSH session into this VM, used to surface idle-time information.
	LastEntry string `json:"last_entry,omitempty"`
}

// AgentState tracks the AI agent process running inside the VM. The fields
// mirror the information previously spread across <profile>.agent.container
// and companion PID files.
type AgentState struct {
	// Type identifies the agent runtime (e.g. "docker", "native").
	Type string `json:"type,omitempty"`

	// ContainerID is the Docker container identifier when the agent runs in a
	// container. Empty for native-process agents.
	ContainerID string `json:"container_id,omitempty"`

	// Version is the image or binary version string of the running agent.
	Version string `json:"version,omitempty"`

	// PID is the host-side process ID of the agent's managing process
	// (e.g. the docker-run wrapper or a native SSH process).
	PID int `json:"pid,omitempty"`

	// StartedAt is the ISO-8601 timestamp of when the agent was last started.
	StartedAt string `json:"started_at,omitempty"`
}

// TunnelState records the parameters and process identity of a single active
// SSH port-forward tunnel. It replaces the flat tunnel-<name>-<profile>.pid
// and <profile>.forward.<port>.pid files.
type TunnelState struct {
	// Name is the human-readable label for the tunnel (e.g. "dev", "api").
	Name string `json:"name"`

	// VMPort is the TCP port being forwarded inside the guest VM.
	VMPort int `json:"vm_port"`

	// HostPort is the local TCP port on the macOS host that receives traffic
	// forwarded from VMPort.
	HostPort int `json:"host_port"`

	// SSHPID is the PID of the ssh(1) process maintaining the tunnel.
	// CleanStaleTunnels removes entries whose SSHPID is no longer alive.
	SSHPID int `json:"ssh_pid"`
}

// SnapshotState records the names and creation timestamps of hypervisor
// snapshots taken for this profile. The factory snapshot serves as a clean
// baseline; the user snapshot captures a personalised checkpoint.
type SnapshotState struct {
	// Factory is the name of the read-only baseline snapshot.
	Factory string `json:"factory,omitempty"`

	// User is the name of the latest user-created checkpoint snapshot.
	User string `json:"user,omitempty"`

	// FactoryCreated is the ISO-8601 timestamp at which the factory snapshot
	// was taken.
	FactoryCreated string `json:"factory_created,omitempty"`

	// UserCreated is the ISO-8601 timestamp at which the user snapshot
	// was taken.
	UserCreated string `json:"user_created,omitempty"`
}

// BaseImageState records which OS image was used to create this profile's VM,
// enabling cloister to detect when a newer base image is available.
type BaseImageState struct {
	// Name is the image identifier as understood by the backend
	// (e.g. a Lume image tag or a Colima template name).
	Name string `json:"name,omitempty"`

	// Created is the ISO-8601 timestamp at which the base image was pulled
	// or built locally.
	Created string `json:"created,omitempty"`
}

// StatePath returns the absolute path of the JSON state file for the given
// profile. The file is stored under ~/.cloister/state/<profile>.json so that
// all per-profile runtime state is co-located and easy to inspect or remove.
func StatePath(profile string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolving home directory: %w", err)
	}
	return filepath.Join(home, ".cloister", "state", profile+".json"), nil
}

// LoadState reads and deserialises the ProfileState from path. When the file
// does not exist, LoadState returns a zero-value ProfileState and a nil error
// so that callers can bootstrap a fresh profile state without a separate
// existence check.
func LoadState(path string) (*ProfileState, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return &ProfileState{}, nil
		}
		return nil, fmt.Errorf("reading state file %s: %w", path, err)
	}

	var state ProfileState
	if err := json.Unmarshal(data, &state); err != nil {
		return nil, fmt.Errorf("parsing state file %s: %w", path, err)
	}
	return &state, nil
}

// SaveState serialises state as indented JSON and writes it atomically to path.
// The write is performed via a sibling temporary file that is then renamed into
// place, ensuring that any concurrent reader either sees the complete previous
// state or the complete new state, never a partially-written document.
func SaveState(path string, state *ProfileState) error {
	data, err := json.MarshalIndent(state, "", "  ")
	if err != nil {
		return fmt.Errorf("serialising state: %w", err)
	}

	// Ensure the parent directory exists before attempting to write.
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating state directory %s: %w", dir, err)
	}

	// Write to a sibling temporary file in the same directory so that the
	// subsequent rename is atomic on POSIX filesystems (same device).
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o600); err != nil {
		return fmt.Errorf("writing temporary state file %s: %w", tmp, err)
	}

	if err := os.Rename(tmp, path); err != nil {
		// Best-effort removal of the orphaned temporary file.
		_ = os.Remove(tmp)
		return fmt.Errorf("committing state file %s: %w", path, err)
	}
	return nil
}

// LoadProfileState resolves the state file path for profile and delegates to
// LoadState. It is the idiomatic entry point for reading profile state.
func LoadProfileState(profile string) (*ProfileState, error) {
	path, err := StatePath(profile)
	if err != nil {
		return nil, err
	}
	return LoadState(path)
}

// SaveProfileState resolves the state file path for profile and delegates to
// SaveState. It is the idiomatic entry point for persisting profile state.
func SaveProfileState(profile string, state *ProfileState) error {
	path, err := StatePath(profile)
	if err != nil {
		return err
	}
	return SaveState(path, state)
}

// CleanStaleTunnels removes tunnel entries from s whose SSH process is no
// longer alive. Liveness is tested by sending signal 0 to the recorded PID
// via os.FindProcess; a non-nil error from Signal(0) indicates the process
// has exited or is otherwise unreachable.
func (s *ProfileState) CleanStaleTunnels() {
	live := s.Tunnels[:0]
	for _, t := range s.Tunnels {
		if isPIDAlive(t.SSHPID) {
			live = append(live, t)
		}
	}
	s.Tunnels = live
}

// isPIDAlive reports whether a process with the given PID is currently alive
// by sending signal 0. A PID of 0 or a negative value is treated as dead
// because neither refers to a valid user-space process.
func isPIDAlive(pid int) bool {
	if pid <= 0 {
		return false
	}
	p, err := os.FindProcess(pid)
	if err != nil {
		return false
	}
	return p.Signal(syscall.Signal(0)) == nil
}

// FindTunnel searches the profile's tunnel list for an entry whose VM-side port
// matches vmPort. It returns a pointer into the slice so callers can update the
// entry in place. Returns nil when no matching tunnel is found.
func (s *ProfileState) FindTunnel(vmPort int) *TunnelState {
	for i := range s.Tunnels {
		if s.Tunnels[i].VMPort == vmPort {
			return &s.Tunnels[i]
		}
	}
	return nil
}

// HostPortInUse reports whether any active tunnel in this profile is already
// bound to the given host-side port. Used to prevent duplicate port allocations
// when establishing a new tunnel.
func (s *ProfileState) HostPortInUse(port int) bool {
	for _, t := range s.Tunnels {
		if t.HostPort == port {
			return true
		}
	}
	return false
}

// NowISO returns the current UTC time formatted as an RFC 3339 string
// (e.g. "2025-01-15T10:30:00Z"). Use this whenever a timestamp field in
// ProfileState or its sub-structs needs to be populated.
func NowISO() string {
	return time.Now().UTC().Format(time.RFC3339)
}
