package colima

import (
	"os"
	"path/filepath"
)

// SSHConfigPath returns the path to the SSH client configuration file that
// Lima (the hypervisor layer beneath Colima) generates for the given profile.
// This file can be passed to `ssh -F` to reach the VM without additional
// parameters. Colima prefixes its own "colima-" to the profile name in the
// Lima directory structure, so the path is:
//
//	~/.colima/_lima/colima-<vmName>/ssh.config
//
// The name SSHConfigPath (rather than SSHConfig) is used here to distinguish
// this path-returning helper from the vm.Backend.SSHConfig() method, which
// returns an SSHAccess struct.
func SSHConfigPath(profile string) string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".colima", "_lima", "colima-"+VMName(profile), "ssh.config")
}

// SSHHost returns the Lima SSH host alias for the given profile. This alias
// is defined inside the ssh.config file generated by Lima and must be used
// as the target hostname when connecting via that config file.
// Format: lima-colima-<vmName>
func SSHHost(profile string) string {
	return "lima-colima-" + VMName(profile)
}
